controllers/SpeechController.php
<?php

namespace app\controllers;

use app\components\CookieUser;
use app\views\speech\LayoutHelper;
use app\models\db\{SpeechQueue, User};
use yii\web\Response;

class SpeechController extends Base
{
    // *** Shared methods ***

    private function getError(string $message): string
    {
        return json_encode([
            'success' => false,
            'message' => $message,
        ]);
    }

    private function getQueue(int $queueId): ?SpeechQueue
    {
        foreach ($this->consultation->speechQueues as $queue) {
            if ($queue->id === $queueId) {
                return $queue;
            }
        }

        return null;
    }

    // *** User-facing methods ***

    public function actionGetQueue(string $queueId)
    {
        $this->handleRestHeaders(['GET'], true);

        \Yii::$app->response->format = Response::FORMAT_RAW;
        \Yii::$app->response->headers->add('Content-Type', 'application/json');

        $user       = User::getCurrentUser();
        $cookieUser = ($user ? null : CookieUser::getFromCookieOrCache());

        $queue = $this->getQueue(intval($queueId));
        if (!$queue) {
            return $this->returnRestResponse(404, $this->getError('Queue not found'));
        }

        $responseJson = json_encode($queue->getUserApiObject($user, $cookieUser));
        return $this->returnRestResponse(200, $responseJson);
    }

    public function actionRegister(string $queueId)
    {
        $this->handleRestHeaders(['POST'], true);

        \Yii::$app->response->format = Response::FORMAT_RAW;
        \Yii::$app->response->headers->add('Content-Type', 'application/json');

        $user = User::getCurrentUser();
        if (!$user) {
            if ($this->consultation->getSettings()->speechRequiresLogin) {
                return $this->returnRestResponse(401, $this->getError('Not logged in'));
            } elseif (\Yii::$app->request->post('username')) {
                $cookieUser = CookieUser::getFromCookieOrCreate(\Yii::$app->request->post('username'));
            } else {
                return $this->returnRestResponse(400, $this->getError('No name provided'));
            }
        } else {
            $cookieUser = null;
        }

        $queue = $this->getQueue(intval($queueId));
        if (!$queue) {
            $this->returnRestResponse(404, $this->getError('Queue not found'));
        }
        if (!$queue->getSettings()->isOpen) {
            return $this->returnRestResponse(403, $this->getError(\Yii::t('speech', 'err_permission_apply')));
        }
        if (count($queue->subqueues) > 0) {
            // Providing a subqueue is necessary if there are some; otherwise, it goes into the "default" subqueue
            $subqueue = $queue->getSubqueueById(intval(\Yii::$app->request->post('subqueue')));
            if (!$subqueue) {
                return $this->returnRestResponse(400, $this->getError('No subqueue provided'));
            }
        } else {
            $subqueue = null;
        }

        if (\Yii::$app->request->post('username')) {
            $name = trim(\Yii::$app->request->post('username'));
        } else {
            $name = $user->name;
        }

        $queue->createItemOnAppliedList($name, $subqueue, $user, $cookieUser);

        $responseJson = json_encode($queue->getUserApiObject($user, $cookieUser));
        return $this->returnRestResponse(200, $responseJson);
    }

    public function actionUnregister(string $queueId)
    {
        $this->handleRestHeaders(['POST'], true);

        \Yii::$app->response->format = Response::FORMAT_RAW;
        \Yii::$app->response->headers->add('Content-Type', 'application/json');

        $user = User::getCurrentUser();
        $cookieUser = CookieUser::getFromCookieOrCache();

        $queue = $this->getQueue(intval($queueId));
        if (!$queue) {
            return $this->returnRestResponse(404, $this->getError('Queue not found'));
        }

        foreach ($queue->items as $item) {
            if ($item->dateStarted) {
                // One can only delete oneself before the speech has started
                continue;
            }
            if (($user && $item->userId === $user->id) || ($cookieUser && $cookieUser->userToken && $item->userToken === $cookieUser->userToken)) {
                /** @noinspection PhpUnhandledExceptionInspection */
                $item->delete();
            }
        }
        $queue->refresh();

        $responseJson = json_encode($queue->getUserApiObject($user, $cookieUser));
        return $this->returnRestResponse(200, $responseJson);
    }

    // *** Admin-facing methods ***

    private function getQueueAndCheckMethodAndPermission(string $queueId): SpeechQueue
    {
        \Yii::$app->response->format = Response::FORMAT_RAW;
        \Yii::$app->response->headers->add('Content-Type', 'application/json');

        $user = User::getCurrentUser();
        if (!$user || !$user->hasPrivilege($this->consultation, User::PRIVILEGE_SPEECH_QUEUES)) {
            $this->returnRestResponse(403, $this->getError('Missing privileges'));
            die();
        }

        $queue = $this->getQueue(intval($queueId));
        if (!$queue) {
            $this->returnRestResponse(404, $this->getError('Queue not found'));
            die();
        }

        return $queue;
    }

    public function actionGetQueueAdmin(string $queueId)
    {
        $this->handleRestHeaders(['GET'], true);
        $queue = $this->getQueueAndCheckMethodAndPermission($queueId);

        $jsonResponse = json_encode($queue->getAdminApiObject());
        return $this->returnRestResponse(200, $jsonResponse);
    }

    public function actionPostQueueSettings(string $queueId)
    {
        $this->handleRestHeaders(['POST'], true);
        $queue = $this->getQueueAndCheckMethodAndPermission($queueId);

        $settings                   = $queue->getSettings();
        $settings->isOpen           = (intval(\Yii::$app->request->post('is_open')) > 0);
        $settings->preferNonspeaker = (intval(\Yii::$app->request->post('prefer_nonspeaker')) > 0);
        $queue->setSettings($settings);

        $queue->isActive = (intval(\Yii::$app->request->post('is_active')) > 0 ? 1 : 0);
        $queue->save();

        if ($queue->isActive) {
            foreach ($this->consultation->speechQueues as $otherQueue) {
                if ($otherQueue->id !== $queue->id) {
                    $otherQueue->isActive = 0;
                    $otherQueue->save();
                }
            }
        }

        $jsonResponse = json_encode([
            'queue'   => $queue->getAdminApiObject(),
            'sidebar' => LayoutHelper::getSidebars($this->consultation, $queue),
        ]);
        return $this->returnRestResponse(200, $jsonResponse);
    }

    public function actionAdminQueueReset(string $queueId)
    {
        $this->handleRestHeaders(['POST'], true);
        $queue = $this->getQueueAndCheckMethodAndPermission($queueId);

        foreach ($queue->items as $item) {
            $item->delete();
        }

        $queue->refresh();
        $jsonResponse = json_encode($queue->getAdminApiObject());
        return $this->returnRestResponse(200, $jsonResponse);
    }

    public function actionPostItemOperation(string $queueId, string $itemId, string $op)
    {
        $this->handleRestHeaders(['POST'], true);
        $queue = $this->getQueueAndCheckMethodAndPermission($queueId);

        $item = $queue->getItemById(intval($itemId));
        if (!$item) {
            return $this->returnRestResponse(404, $this->getError('Item not found'));
        }

        switch ($op) {
            case "set-slot":
                $maxPosition = 0;
                foreach ($queue->items as $cmpItem) {
                    if ($cmpItem->position !== null && $cmpItem->position > $maxPosition) {
                        $maxPosition = $cmpItem->position;
                    }
                }

                $item->position    = $maxPosition + 1;
                $item->dateStarted = null;
                $item->dateStopped = null;
                $item->save();
                break;
            case "unset-slot":
                $item->position    = null;
                $item->dateStarted = null;
                $item->dateStopped = null;
                $item->save();
                break;
            case "set-slot-and-start":
                $maxPosition = 0;
                foreach ($queue->items as $cmpItem) {
                    if ($cmpItem->position !== null && $cmpItem->position > $maxPosition) {
                        $maxPosition = $cmpItem->position;
                    }
                }

                $item->position    = $maxPosition + 1;
                $item->dateStarted = date("Y-m-d H:i:s");
                $item->dateStopped = null;
                $item->save();

                foreach ($queue->items as $cmpItem) {
                    if ($cmpItem->id !== $item->id && $cmpItem->dateStarted !== null && $cmpItem->dateStopped === null) {
                        $cmpItem->dateStopped = date("Y-m-d H:i:s");
                        $cmpItem->save();
                    }
                }
                break;
            case "start":
                $item->dateStarted = date("Y-m-d H:i:s");
                $item->dateStopped = null;
                $item->save();

                foreach ($queue->items as $cmpItem) {
                    if ($cmpItem->id !== $item->id && $cmpItem->dateStarted !== null && $cmpItem->dateStopped === null) {
                        $cmpItem->dateStopped = date("Y-m-d H:i:s");
                        $cmpItem->save();
                    }
                }
                break;
            case "stop":
                $item->dateStopped = date("Y-m-d H:i:s");
                $item->save();
                break;
            case "move":
                $newPosition = \Yii::$app->request->post('position');

views/speech/LayoutHelper.php
<?php

namespace app\views\speech;

use app\components\UrlHelper;
use app\models\db\{Consultation, Motion, SpeechQueue};
use yii\helpers\Html;

class LayoutHelper
{
    private static function addQueueToSidebar(SpeechQueue $speechQueue, ?Motion $motion, string &$mainHtml, string &$miniHtml, SpeechQueue $selectedQueue)
    {
        if ($motion) {
            $url = UrlHelper::createMotionUrl($motion, 'admin-speech');
        } else {
            $url = UrlHelper::createUrl(['consultation/admin-speech']);
        }

        if ($speechQueue->isActive) {
            $mainHtml .= '<li class="active">';
            $mainHtml .= '<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>';
        } else {
            $mainHtml .= '<li>';
        }
        if ($selectedQueue->id === $speechQueue->id) {
            $mainHtml .= Html::encode($speechQueue->getTitle());
        } else {
            $mainHtml .= Html::a(Html::encode($speechQueue->getTitle()), $url);
        }
        if ($speechQueue->isActive) {
            $mainHtml .= '<div class="activeLabel">' . \Yii::t('speech', 'sidebar_active') . '</div>';
        }
        $mainHtml .= '</li>';
    }

    public static function getSidebars(Consultation $consultation, SpeechQueue $currentQueue): array
    {
        if (count($consultation->speechQueues) < 2) {
            return ['', ''];
        }
        $miniHtml = '';

        $html = '<section class="sidebar-box otherQueues" aria-labelledby="sidebarOtherQueues"><ul class="nav nav-list">';
        $html .= '<li class="nav-header" id="sidebarOtherQueues">' . \Yii::t('speech', 'sidebar_title') . '</li>';

        foreach ($consultation->speechQueues as $speechQueue) {
            if ($speechQueue->motionId === null) {
                static::addQueueToSidebar($speechQueue, null, $html, $miniHtml, $currentQueue);
            }
        }
        foreach ($consultation->getVisibleMotionsSorted() as $motion) {
            foreach ($consultation->speechQueues as $speechQueue) {
                if ($speechQueue->motionId === $motion->id) {
                    static::addQueueToSidebar($speechQueue, $motion, $html, $miniHtml, $currentQueue);
                }
            }
        }

        $html .= '</ul></section>';

        return [$html, $miniHtml];
    }
}

views/speech/_footer_widget.php
<?php

use app\components\UrlHelper;
use app\models\db\User;
use yii\helpers\Html;

/**
 * @var \yii\web\View $this
 * @var \app\models\db\SpeechQueue $queue
 */

if (!$queue) {
    return;
}

/** @var \app\controllers\Base $controller */
$controller = $this->context;
$consultation = $controller->consultation;
$layout = $controller->layoutParams;
$user = User::getCurrentUser();
$cookieUser = ($user ? null : \app\components\CookieUser::getFromCookieOrCache());

$layout->loadVue();
$layout->addVueTemplate('@app/views/speech/user-footer-widget.vue.php');

$initData = $queue->getUserApiObject($user, $cookieUser);
if ($user) {
    $userData = [
        'logged_in' => true,
        'id'        => $user->id,
        'token'     => null,
        'name'      => $user->name,
    ];
} elseif ($cookieUser) {
    $userData = [
        'logged_in' => true,
        'id'        => null,
        'token'     => $cookieUser->userToken,
        'name'      => $cookieUser->name,
    ];
} else {
    $userData = [
        'logged_in' => false,
        'id'        => null,
        'token'     => null,
        'name'      => '',
    ];
}

$user = User::getCurrentUser();
if ($user && $user->hasPrivilege($consultation, User::PRIVILEGE_SPEECH_QUEUES)) {
    $adminUrl = UrlHelper::createUrl(['consultation/admin-speech']);
} else {
    $adminUrl = '';
}

?>
<section aria-labelledby="speechListUserTitle"
         data-antragsgruen-widget="frontend/CurrentSpeechList" class="currentSpeechFooter"
         data-queue="<?= Html::encode(json_encode($initData)) ?>"
         data-user="<?= Html::encode(json_encode($userData)) ?>"
         data-title="<?= Html::encode($queue->getTitleShort()) ?>"
         data-admin-url="<?= Html::encode($adminUrl) ?>"
>
    <div class="hidden" id="speechListUserTitle"><?= Html::encode($queue->getTitle()) ?></div>
    <div class="currentSpeechList"></div>
</section>

views/speech/_index_speech.php
<?php

use app\components\UrlHelper;
use app\models\db\User;
use yii\helpers\Html;

/**
 * @var \yii\web\View $this
 * @var \app\models\db\SpeechQueue $queue
 */

if (!$queue) {
    return;
}

/** @var \app\controllers\Base $controller */
$controller = $this->context;
$consultation = $controller->consultation;
$layout = $controller->layoutParams;
$user = User::getCurrentUser();
$cookieUser = ($user ? null : \app\components\CookieUser::getFromCookieOrCache());

$layout->loadVue();
$layout->addVueTemplate('@app/views/speech/user-inline-widget.vue.php');

$initData = $queue->getUserApiObject($user, $cookieUser);
if ($user) {
    $userData = [
        'logged_in' => true,
        'id'        => $user->id,
        'token'     => null,
        'name'      => $user->name,
    ];
} elseif ($cookieUser) {
    $userData = [
        'logged_in' => true,
        'id'        => null,
        'token'     => $cookieUser->userToken,
        'name'      => $cookieUser->name,
    ];
} else {
    $userData = [
        'logged_in' => false,
        'id'        => null,
        'token'     => null,
        'name'      => '',
    ];
}

?>
<section aria-labelledby="speechListUserTitle"
         data-antragsgruen-widget="frontend/CurrentSpeechList" class="currentSpeechInline"
         data-queue="<?= Html::encode(json_encode($initData)) ?>"
         data-user="<?= Html::encode(json_encode($userData)) ?>"
         data-title="<?= Html::encode($queue->getTitle()) ?>"
>
    <h2 class="green" id="speechListUserTitle"><?= Yii::t('speech', 'user_section_title') ?></h2>
    <div class="content">
        <?php
        $user = User::getCurrentUser();
        if ($user && $user->hasPrivilege($consultation, User::PRIVILEGE_SPEECH_QUEUES)) {
            $url = UrlHelper::createUrl(['consultation/admin-speech']);
            echo '<a href="' . Html::encode($url) . '" class="speechAdminLink">';
            echo '<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> ';
            echo Yii::t('speech', 'goto_admin');
            echo '</a>';
        }
        ?>
        <div class="currentSpeechList"></div>
    </div>
</section>

views/speech/admin-singlepage.php
<?php

use app\components\UrlHelper;
use app\models\db\SpeechQueue;
use yii\helpers\Html;

/**
 * @var \yii\web\View $this
 * @var SpeechQueue $queue
 */

/** @var \app\controllers\Base $controller */
$controller = $this->context;
/** @var \app\models\db\Consultation */
$consultation = $controller->consultation;
$layout       = $controller->layoutParams;
if ($queue->motion) {
    $layout->addBreadcrumb($queue->motion->getBreadcrumbTitle(), UrlHelper::createMotionUrl($queue->motion));
}
$layout->addBreadcrumb(Yii::t('speech', 'admin_bc'));

$layout->loadVue();
$layout->addVueTemplate('@app/views/speech/admin-widget.vue.php');
$layout->addVueTemplate('@app/views/speech/admin-subqueue.vue.php');

$htmls = \app\views\speech\LayoutHelper::getSidebars($consultation, $queue);
if ($htmls[0] !== '') {
    $layout->menusHtml[] = $htmls[0];
}
if ($htmls[1] !== '') {
    $layout->menusHtmlSmall[] = $htmls[1];
}

$initData = $queue->getAdminApiObject();

if ($queue->motion) {
    $this->title = str_replace('%TITLE%', $queue->motion->titlePrefix, Yii::t('speech', 'admin_title_to'));
} else {
    $this->title = Yii::t('speech', 'admin_title_plain');
}
?>
<h1><?= Html::encode($this->title) ?></h1>
<div class="manageSpeechQueue">
    <section data-antragsgruen-widget="backend/SpeechListEdit"
             data-queue="<?= Html::encode(json_encode($initData)) ?>">
        <div class="speechAdmin"></div>
    </section>
</div>

views/speech/user-footer-widget.vue.php
<?php

use app\components\UrlHelper;
use yii\helpers\Html;

$loginUrl = UrlHelper::createUrl(['user/login', 'backUrl' => Yii::$app->request->url]);

ob_start();
?>

<article class="speechUser">
    <header class="widgetTitle">
        {{ title }}
        <a v-if="adminUrl" :href="adminUrl" class="speechAdminLink">
            <span class="glyphicon glyphicon-wrench" title="<?= Html::encode(Yii::t('speech', 'goto_admin')) ?>" aria-label="<?= Html::encode(Yii::t('speech', 'goto_admin')) ?>"></span>
        </a>
    </header>

    <div class="activeSpeaker">
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        <span class="title"><?= Yii::t('speech', 'footer_current') ?>:</span>
        <span class="name" v-if="activeSpeaker">
            {{ activeSpeaker.name }}
            <span class="label label-success" v-if="isMe(activeSpeaker)"><?= Yii::t('speech', 'you') ?></span>
        </span>
        <span class="nobody" v-if="!activeSpeaker">
            <?= Yii::t('speech', 'footer_current_nobody') ?>
        </span>
    </div>
    <div v-if="upcomingSpeakers.length > 0" class="upcomingSpeaker">
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        <?= Yii::t('speech', 'next_speaker') ?>:
        <ul class="upcomingSpeakerList">
            <li v-for="speaker in upcomingSpeakers">
                <span class="name">{{ speaker.name }}</span><!-- Fight unwanted whitespace
                --><span class="label label-success" v-if="isMe(speaker)"><?= Yii::t('speech', 'you') ?></span><!-- Fight unwanted whitespace
                -->
                <button type="button" class="btn btn-link btnWithdraw" v-if="isMe(speaker)" @click="removeMeFromQueue($event)"
                        title="<?= Yii::t('speech', 'apply_revoke_aria') ?>" aria-label="<?= Yii::t('speech', 'apply_revoke_aria') ?>">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    <span class="withdrawLabel"><?= Yii::t('speech', 'apply_revoke') ?></span>
                </button>
            </li>
        </ul>
    </div>

    <section class="waiting waitingSingle" v-if="queue.subqueues.length === 1" aria-label="<?= Yii::t('speech', 'waiting_aria_1') ?>">
        <header>
            <div v-if="queue.subqueues[0].have_applied" class="appliedMe">
                <span class="label label-success" aria-label="<?= Yii::t('speech', 'applied_aria') ?>"><?= Yii::t('speech', 'applied') ?></span>
                <button type="button" class="btn btn-link btnWithdraw" @click="removeMeFromQueue($event)"
                        title="<?= Yii::t('speech', 'apply_revoke_aria') ?>" aria-label="<?= Yii::t('speech', 'apply_revoke_aria') ?>">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    <span class="withdrawLabel"><?= Yii::t('speech', 'apply_revoke') ?></span>
                </button>
            </div>

            <button class="btn btn-default btn-xs" type="button"
                    v-if="!queue.have_applied && showApplicationForm !== queue.subqueues[0].id && !loginWarning"
                    @click="onShowApplicationForm($event, queue.subqueues[0])"
            >
                <?= Yii::t('speech', 'apply') ?>
            </button>
            <a href="<?= Html::encode($loginUrl) ?>" class="loginWarning" v-if="loginWarning">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <?= Yii::t('speech', 'login_warning') ?>
            </a>

            <form @submit="register($event, queue.subqueues)" v-if="!queue.subqueues[0].have_applied && showApplicationForm === queue.subqueues[0].id">
                <label :for="'speechRegisterName' + queue.subqueues[0].id" class="sr-only"><?= Yii::t('speech', 'apply_name') ?></label>
                <div class="input-group">
                    <input type="text" class="form-control" v-model="registerName" :id="'speechRegisterName' + queue.subqueues[0].id"
                           ref="adderNameInput">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><?= Yii::t('speech', 'apply_do') ?></button>
                    </span>
                </div>
            </form>
        </header>
    </section>

    <section class="waiting waitingMultiple" v-if="queue.subqueues.length > 1" aria-label="<?= Yii::t('speech', 'waiting_aria_x') ?>">
        <div v-for="subqueue in queue.subqueues" class="subqueue">
            <div class="name" v-if="showApplicationForm !== subqueue.id">
                <span class="glyphicon glyphicon-time" aria-label="<?= Yii::t('speech', 'waiting_list') ?>"></span>
                {{ subqueue.name }}
            </div>

            <div class="number" v-if="showApplicationForm !== subqueue.id" :aria-label="numAppliedTitle(subqueue)" :title="numAppliedTitle(subqueue)">{{ subqueue.num_applied }}</div>

            <div v-if="subqueue.have_applied && showApplicationForm !== subqueue.id" class="appliedMe">
                <span class="label label-success" aria-label="<?= Yii::t('speech', 'applied_aria') ?>"><?= Yii::t('speech', 'applied') ?></span>
                <button type="button" class="btn btn-link btnWithdraw" @click="removeMeFromQueue($event)"
                        title="<?= Yii::t('speech', 'apply_revoke_aria') ?>" aria-label="<?= Yii::t('speech', 'apply_revoke_aria') ?>">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    <span class="withdrawLabel"><?= Yii::t('speech', 'apply_revoke') ?></span>
                </button>
            </div>

            <button class="btn btn-default btn-xs applyBtn" type="button"
                    v-if="queue.is_open && !queue.have_applied && showApplicationForm !== subqueue.id && !loginWarning"
                    @click="onShowApplicationForm($event, subqueue)"
            >
                <?= Yii::t('speech', 'apply') ?>
            </button>
            <a href="<?= Html::encode($loginUrl) ?>" class="loginWarning" v-if="loginWarning">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <?= Yii::t('speech', 'login_warning') ?>
            </a>

            <form @submit="register($event, subqueue)" v-if="queue.is_open && !queue.have_applied && showApplicationForm === subqueue.id">
                <label :for="'speechRegisterName' + subqueue.id" class="sr-only"><?= Yii::t('speech', 'apply_name') ?></label>
                <div class="input-group">
                    <input type="text" class="form-control" v-model="registerName" :id="'speechRegisterName' + subqueue.id" ref="adderNameInput">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><?= Yii::t('speech', 'apply_do') ?></button>
                    </span>
                </div>
            </form>
        </div>
    </section>
</article>


<?php
$html          = ob_get_clean();
$pollUrl       = UrlHelper::createUrl(['/speech/get-queue', 'queueId' => 'QUEUEID']);
$registerUrl   = UrlHelper::createUrl(['/speech/register', 'queueId' => 'QUEUEID']);
$unregisterUrl = UrlHelper::createUrl(['/speech/unregister', 'queueId' => 'QUEUEID']);
?>

<script>
    const pollUrl = <?= json_encode($pollUrl) ?>;
    const registerUrl = <?= json_encode($registerUrl) ?>;
    const unregisterUrl = <?= json_encode($unregisterUrl) ?>;

    Vue.component('speech-user-footer-widget', {
        template: <?= json_encode($html) ?>,
        props: ['queue', 'csrf', 'user', 'title', 'adminUrl'],
        data() {
            return {
                registerName: this.user.name,
                showApplicationForm: false, // "null" is already taken by the default form
                pollingId: null
            };
        },
        computed: {
            activeSpeaker: function () {
                const active = this.queue.slots.filter(function (slot) {
                    return slot.date_stopped === null && slot.date_started !== null;
                });
                return (active.length > 0 ? active[0] : null);
            },
            upcomingSpeakers: function () {
                return this.queue.slots.filter(function (slot) {
                    return slot.date_stopped === null && slot.date_started === null;
                });
            },
            loginWarning: function () {
                return this.queue.requires_login && !this.user.logged_in;
            }
        },
        methods: {
            isMe: function (slot) {
                return slot.userId === this.user.id;
            },
            numAppliedTitle: function (subqueue) {
                if (subqueue.num_applied === 1) {
                    const msg = "" + <?= json_encode(Yii::t('speech', 'persons_waiting_1')) ?>;
                    return msg;
                } else {
                    const msg = "" + <?= json_encode(Yii::t('speech', 'persons_waiting_x')) ?>;
                    return msg.replace(/%NUM%/, subqueue.num_applied);
                }
            },
            register: function ($event, subqueue) {
                $event.preventDefault();

                const widget = this;
                $.post(registerUrl.replace(/QUEUEID/, widget.queue.id), {
                    subqueue: subqueue.id,
                    username: this.registerName,
                    _csrf: this.csrf,
                }, function (data) {
                    widget.queue = data;
                    widget.showApplicationForm = false;
                }).catch(function (err) {
                    alert(err.responseText);
                });
            },
            onShowApplicationForm: function ($event, subqueue) {
                $event.preventDefault();

                this.showApplicationForm = subqueue.id;
                this.$nextTick(function () {
                    this.$refs.adderNameInput[0].focus();
                });
            },
            removeMeFromQueue: function ($event) {
                $event.preventDefault();

                const widget = this;
                $.post(unregisterUrl.replace(/QUEUEID/, widget.queue.id), {
                    _csrf: this.csrf,
                }, function (data) {
                    widget.queue = data;
                }).catch(function (err) {
                    alert(err.responseText);
                });
            },
            reloadData: function () {
                const widget = this;
                $.get(pollUrl.replace(/QUEUEID/, widget.queue.id), function (data) {
                    widget.queue = data;
                }).catch(function(err) {
                    console.error("Could not load speech queue data from backend", err);
                });
            },
            startPolling: function () {
                const widget = this;
                this.pollingId = window.setInterval(function () {
                    widget.reloadData();
                }, 3000);
            }
        },
        beforeDestroy() {
            window.clearInterval(this.pollingId)
        },
        created() {
            this.startPolling()
        }
    });
</script>