controllers/UserController.php
<?php

namespace app\controllers;

use app\components\{ConsultationAccessPassword, Tools, UrlHelper, WurzelwerkSamlClient};
use app\models\db\{AmendmentSupporter, ConsultationUserPrivilege, EMailBlocklist, MotionSupporter, User, UserNotification};
use app\models\events\UserEvent;
use app\models\exceptions\{ExceptionBase, FormError, Login, MailNotSent, ServerConfiguration};
use app\models\forms\LoginUsernamePasswordForm;
use app\models\settings\AntragsgruenApp;
use Yii;
use yii\helpers\Html;
use yii\web\Response;

class UserController extends Base
{
    public $enableCsrfValidation = false;

    /**
     * @return array
     */
    public function actions()
    {
        return [
            'auth' => [
                'class'           => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successCallback'],
            ],
        ];
    }

    /**
     * @param User $user
     */
    protected function loginUser(User $user)
    {
        Yii::$app->user->login($user, $this->getParams()->autoLoginDuration);
    }

    public function actionLoginsaml(string $backUrl = ''): string
    {
        /** @var AntragsgruenApp $params */
        $params = Yii::$app->params;
        if (!$params->isSamlActive()) {
            return 'SAML is not supported';
        }

        if ($backUrl == '') {
            $backUrl = Yii::$app->request->post('backUrl', UrlHelper::homeUrl());
        }

        try {
            $samlClient = new WurzelwerkSamlClient();
            $samlClient->requireAuth();

            $this->loginUser($samlClient->getOrCreateUser());

            $this->redirect($backUrl);
        } catch (\Exception $e) {
            $this->showErrorpage(
                500,
                Yii::t('user', 'err_unknown') . ':<br> "' . Html::encode($e->getMessage()) . '"'
            );
        }

        return '';
    }

    /**
     * @param string $backUrl
     * @return string
     * @throws \yii\base\ExitException
     */
    public function actionLogin($backUrl = '')
    {
        $this->layout = 'column2';

        if ($backUrl === '') {
            $backUrl = '/';
        }

        $usernamePasswordForm = new LoginUsernamePasswordForm(User::getExternalAuthenticator());

        $conPwdConsultation = $this->consultation;
        if (Yii::$app->request->get('passConId')) {
            foreach ($this->site->consultations as $consultation) {
                if ($consultation->urlPath === Yii::$app->request->get('passConId')) {
                    $conPwdConsultation = $consultation;
                }
            }
        }

        if ($this->isPostSet('loginusernamepassword')) {
            $usernamePasswordForm->setAttributes(Yii::$app->request->post());
            try {
                $user = $usernamePasswordForm->getOrCreateUser($this->site);
                $this->loginUser($user);

                $unconfirmed = ($user->status === User::STATUS_UNCONFIRMED);
                if ($unconfirmed && $this->getParams()->confirmEmailAddresses) {
                    $backUrl = UrlHelper::createUrl([
                        'user/confirmregistration',
                        'backUrl' => $backUrl,
                        'email'   => $user->email,
                    ]);
                } else {
                    Yii::$app->session->setFlash('success', Yii::t('user', 'welcome'));
                }

                /* 307 breaks user/NoEmailConfirmationCept
                $this->redirect($backUrl, 307);
                Yii::$app->end(307);
                */
                $this->redirect($backUrl);
                Yii::$app->end(302);
            } catch (Login $e) {
                $usernamePasswordForm->error = $e->getMessage();
            }
        }

        $conPwdErr = null;
        if ($this->isPostSet('loginconpwd') && $conPwdConsultation) {
            $conPwd = new ConsultationAccessPassword($conPwdConsultation);
            if ($conPwd->checkPassword(Yii::$app->request->post('password'))) {
                $conPwd->setCorrectCookie();
                $this->redirect($backUrl);
                Yii::$app->end(302);
            } else {
                $conPwdErr = 'Invalid password';
            }
        }

        if (Yii::$app->session->isActive && Yii::$app->session->getFlash('error')) {
            $usernamePasswordForm->error = Yii::$app->session->getFlash('error');
            Yii::$app->session->removeFlash('error');
        }


        return $this->render(
            'login',
            [
                'backUrl'              => $backUrl,
                'usernamePasswordForm' => $usernamePasswordForm,
                'conPwdConsultation'   => $conPwdConsultation,
                'conPwdErr'            => $conPwdErr,
            ]
        );
    }

    /**
     * @param string $backUrl
     * @param string $email
     * @return string
     */
    public function actionConfirmregistration($backUrl = '', $email = '')
    {
        $msgError = '';

        if ($this->isRequestSet('email') && $this->isRequestSet('code')) {
            /** @var User $user */
            $user = User::findOne(['auth' => 'email:' . $this->getRequestValue('email')]);
            if (!$user) {
                $msgError = Yii::t('user', 'err_email_acc_notfound');
            } elseif ($user->checkEmailConfirmationCode(trim($this->getRequestValue('code')))) {
                $user->emailConfirmed = 1;
                $user->status         = User::STATUS_CONFIRMED;
                if ($user->save()) {
                    $user->trigger(User::EVENT_ACCOUNT_CONFIRMED, new UserEvent($user));
                    $this->loginUser($user);

                    if ($this->consultation && $this->consultation->getSettings()->managedUserAccounts) {
                        ConsultationUserPrivilege::askForConsultationPermission($user, $this->consultation);
                        $needsAdminScreening = true;
                    } else {
                        $needsAdminScreening = false;
                    }

                    return $this->render('registration_confirmed', ['needsAdminScreening' => $needsAdminScreening]);
                }
            } else {
                $msgError = Yii::t('user', 'err_code_wrong');
            }
        }

        return $this->render(
            'confirm_registration',
            [
                'email'   => $email,
                'errors'  => $msgError,
                'backUrl' => $backUrl
            ]
        );
    }

    private function logoutSaml(string $backUrl = ''): string
    {
        try {
            /** @var AntragsgruenApp $params */
            $params        = Yii::$app->params;
            $backSubdomain = UrlHelper::getSubdomain($backUrl);
            $currDomain    = $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['HTTP_HOST'];
            $currSubdomain = UrlHelper::getSubdomain($currDomain);

            if ($currSubdomain) {
                // First step on the subdomain: logout and redirect to the main domain
                Yii::$app->user->logout();
                $backParts = parse_url($backUrl);
                if (!isset($backParts['host'])) {
                    $backUrl = $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['HTTP_HOST'] . $backUrl;
                }
                $this->redirect($params->domainPlain . 'user/logout?backUrl=' . urlencode($backUrl));
            } elseif ($backSubdomain) {
                // Second step: we are on the main domain. Logout and redirect to the subdomain
                $samlClient = new WurzelwerkSamlClient();
                $samlClient->logout();
                $this->redirect($backUrl);
            } else {
                // No subdomain is involved, local logout on the main domain
                $samlClient = new WurzelwerkSamlClient();
                $samlClient->logout();
                $this->redirect($backUrl);
            }
        } catch (\Exception $e) {
            $this->showErrorpage(
                500,
                Yii::t('user', 'err_unknown') . ':<br> "' . Html::encode($e->getMessage()) . '"'
            );
        }
        return '';
    }


    public function actionLogout(string $backUrl = ''): string
    {
        /** @var AntragsgruenApp $params */
        $params = Yii::$app->params;

        if ($backUrl == '') {
            $backUrl = Yii::$app->request->post('backUrl', UrlHelper::homeUrl());
        }

        if ($params->isSamlActive()) {
            return $this->logoutSaml($backUrl);
        } else {
            Yii::$app->user->logout();
            $this->redirect($backUrl, 307);
            return '';
        }
    }

    public function actionRecovery(string $email = '', string $code = ''): string
    {
        if ($this->isPostSet('send')) {
            /** @var User $user */
            $user = User::findOne(['auth' => 'email:' . $this->getRequestValue('email')]);
            if (!$user) {
                $msg = str_replace('%USER%', $this->getRequestValue('email'), Yii::t('user', 'err_user_notfound'));
                Yii::$app->session->setFlash('error', $msg);
            } else {
                $email = $this->getRequestValue('email');
                try {
                    $user->sendRecoveryMail();
                    $msg = Yii::t('user', 'pwd_recovery_sent');
                    Yii::$app->session->setFlash('success', $msg);
                } catch (MailNotSent | ServerConfiguration | FormError $e) {
                    $errMsg = Yii::t('base', 'err_email_not_sent') . ': ' . $e->getMessage();
                    Yii::$app->session->setFlash('error', $errMsg);
                }
            }
        }

        if ($this->isPostSet('recover')) {
            /** @var User $user */
            $user     = User::findOne(['auth' => 'email:' . $this->getRequestValue('email')]);
            $pwMinLen = LoginUsernamePasswordForm::PASSWORD_MIN_LEN;
            if (!$user) {

views/user/account_deleted.php
<?php

/**
 * @var yii\web\View $this
 * @var \app\models\db\Site $site
 * @var bool $policyWarning
 */

/** @var \app\controllers\Base $controller */
$controller = $this->context;
$layout     = $controller->layoutParams;

$this->title = Yii::t('user', 'deleted_title');
?>
<h1><?= Yii::t('user', 'deleted_title') ?></h1>
<div class="content">
    <div class="alert alert-success" role="alert">
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
        <span class="sr-only"><?= Yii::t('base', 'aria_success') ?>:</span>
        <?= Yii::t('user', 'deleted_msg') ?>
    </div>
</div>

views/user/confirm_registration.php
<?php

use app\components\UrlHelper;
use yii\helpers\Html;

/**
 * @var $this yii\web\View
 * @var string $errors
 * @var string $backUrl
 * @var string $email
 */

$this->title = Yii::t('user', 'confirm_title');

echo '<h1>' . Yii::t('user', 'confirm_title') . '</h1>
<div class="content">';

if ($errors != '') {
    echo '<div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">' . Yii::t('base', 'aria_error') . ':</span>' . Html::encode($errors) . '</div>';
} else {
    echo '<div class="alert alert-info" role="alert">
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
        ' . Yii::t('user', 'confirm_mail_sent') . '
    </div>';
}

$params = ['user/confirmregistration', 'backUrl' => $backUrl];
if ($email) {
    $params['email'] = $email;
}
echo Html::beginForm(UrlHelper::createUrl($params), 'post', ['id' => 'confirmAccountForm']);

echo '<div class="row"><div class="form-group col-md-6">
    <label for="username">' . Yii::t('user', 'confirm_username') . ':</label>
    <input type="text" value="' . Html::encode($email) . '" id="username" name="email" class="form-control" ';
if ($email != '') {
    echo "disabled";
}
echo '>
        </div></div>

    <div class="row"><div class="form-group col-md-6">
        <label for="code">' . Yii::t('user', 'confirm_code') . ':</label>
        <input type="text" name="code" value="" id="code" class="form-control">
    </div></div>

    <div class="row"><div class="col-md-6">
        <input type="submit" value="' . Yii::t('user', 'confirm_btn_do') . '" class="btn btn-primary">
    </div></div>
    ';

echo Html::endForm();

echo '</div>';

views/user/email_blocklist.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var bool $isBlocked
 */

/** @var \app\controllers\UserController $controller */
$controller = $this->context;
$consultation = $controller->consultation;
$layout = $controller->layoutParams;

$this->title = Yii::t('user', 'no_noti_title');
$layout->addBreadcrumb(Yii::t('user', 'no_noti_bc'));
$layout->robotsNoindex = true;


echo '<h1>' . Yii::t('user', 'no_noti_title') . '</h1>';

echo Html::beginForm('', 'post', ['class' => 'emailBlocklistForm content']);

echo $controller->showErrors();

?>
<div class="radio">
    <label>
        <?= Html::radio('unsubscribeOption', false, ['class' => 'unsubscribeNone', 'value' => 'nothing']) ?>
        <?= Yii::t('user', 'no_noti_unchanged') ?>
    </label>
</div>
<?php if ($consultation) { ?>
    <div class="radio">
        <label>
            <?= Html::radio('unsubscribeOption', true, ['class' => 'unsubscribeConsultation', 'value' => 'consultation']) ?>
            <?= str_replace('%NAME%', $consultation->title, Yii::t('user', 'no_noti_consultation')) ?>
        </label>
    </div>
<?php } ?>

<div class="radio">
    <label>
        <?= Html::radio('unsubscribeOption', false, ['class' => 'unsubscribeAll', 'value' => 'all']) ?>
        <?= Yii::t('user', 'no_noti_all') ?>
    </label>
</div>

<br>

<div class="checkbox">
    <label>
        <?= Html::checkbox('emailBlocklist', $isBlocked, ['class' => 'emailBlocklist']) ?>
        <?= Yii::t('user', 'no_noti_blocklist') ?>
    </label>
</div>

<br>

<div class="saveholder">
    <button type="submit" name="save" class="btn btn-primary"><?= Yii::t('user', 'no_noti_save') ?></button>
</div>

<br><br>

<?= Html::endForm() ?>

views/user/login.php
<?php

use app\components\UrlHelper;
use app\models\db\User;
use app\models\forms\LoginUsernamePasswordForm;
use yii\helpers\Html;
use app\models\settings\Site as SiteSettings;

/**
 * @var yii\web\View $this
 * @var LoginUsernamePasswordForm $usernamePasswordForm
 * @var string $backUrl
 * @var string|null $conPwdErr
 * @var \app\models\db\Consultation $conPwdConsultation
 */

/** @var \app\controllers\UserController $controller */
$controller = $this->context;
$layout     = $controller->layoutParams;

$this->title = Yii::t('user', 'login_title');
$layout->addBreadcrumb(Yii::t('user', 'login_title'));
$layout->robotsNoindex = true;
$layout->addAMDModule('frontend/LoginForm');

if ($controller->site) {
    $loginMethods = $controller->site->getSettings()->loginMethods;
} else {
    $loginMethods = SiteSettings::$SITE_MANAGER_LOGIN_METHODS;
}
/** @var \app\models\settings\AntragsgruenApp $params */
$params = Yii::$app->params;

$externalAuthenticator = User::getExternalAuthenticator();

echo '<h1>' . Yii::t('user', 'login_title') . '</h1>';

$loginText = \app\models\db\ConsultationText::getPageData($controller->site, $controller->consultation, 'login_pre');
if ($loginText && trim($loginText->text) !== '') {
    echo '<div class="content contentPage">';
    echo $loginText->text;
    echo '</div>';
}

$shownAccessPwdForm = false;
if ($controller->consultation && $controller->consultation->getSettings()->accessPwd) {
    $conPwd = new \app\components\ConsultationAccessPassword($controller->consultation);
    if (!$conPwd->isCookieLoggedIn()) {
        $shownAccessPwdForm = true;
        ?>
        <section class="loginConPwd">
            <h2 class="green"><?= Yii::t('user', 'login_con_pwd_title') ?></h2>
            <?= Html::beginForm('', 'post', ['class' => 'content row', 'id' => 'conPwdForm']) ?>
            <div class="content">
                <?php
                if ($conPwdErr) {
                    echo '<div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">' . Yii::t('base', 'aria_error') . ':</span>';
                    echo Html::encode($conPwdErr);
                    echo '</div>';
                }
                ?>
                <div class="row content">
                    <label><?= Yii::t('motion', 'consultation') ?>:</label>
                    <div>
                        <?= Html::encode($conPwdConsultation->title) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="conpwd"><?= Yii::t('user', 'login_con_pwd') ?>:</label>
                        <input type="password" value="" name="password" id="conpwd" class="form-control"
                               autocomplete="current-password">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-primary" name="loginconpwd">
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                            <?= Yii::t('user', 'login_btn_login') ?>
                        </button>
                    </div>
                </div>
            </div>
            <?php
            if (in_array(SiteSettings::LOGIN_STD, $loginMethods)) {
                echo '<div class="usernameLoginOpener" style="padding-left: 20px;">
                    <a href="#" onClick="$(\'.loginUsername\').toggleClass(\'hidden\'); $(\'#username\').trigger(\'focus\').scrollintoview({top_offset: 100}); return false;">' .
                     Yii::t('user', 'login_username_title') .
                     '</a>
                </div>';
            }
            ?>
            <?= Html::endForm() ?>
        </section>
        <?php
    }
}

if (in_array(SiteSettings::LOGIN_STD, $loginMethods)) {
    $pwMinLen         = LoginUsernamePasswordForm::PASSWORD_MIN_LEN;
    $supportsCreating = ($externalAuthenticator === null || $externalAuthenticator->supportsCreatingAccounts());

    $classes = ['loginUsername'];
    if ($shownAccessPwdForm) {
        $classes[] = 'hidden';
    }

    echo '<section class="' . implode(' ', $classes) . '">
    <h2 class="green">' . Yii::t('user', 'login_username_title') . '</h2>
    <div class="content row">';

    if ($usernamePasswordForm->error) {
        echo '<div class="alert alert-danger" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>';
        echo Html::encode($usernamePasswordForm->error);
        echo '</div>';
    }

    echo Html::beginForm('', 'post', ['class' => 'col-sm-6', 'id' => 'usernamePasswordForm']);

    $preUsername = $usernamePasswordForm->username;
    $preName     = $usernamePasswordForm->name;

    if ($supportsCreating) {
        $preChecked = (isset($_REQUEST["createAccount"]) ? 'checked' : '');
        ?>
        <div class="checkbox">
            <label>
                <input type="checkbox" name="createAccount" id="createAccount" <?= $preChecked ?>>
                <?= Yii::t('user', 'login_create_account') ?>
            </label>
        </div>
        <?php
    }

    if ($controller->consultation && $controller->consultation->getSettings()->managedUserAccounts) {
        echo '<div class="alert alert-info managedAccountHint hidden"><p>';
        echo Yii::t('user', 'login_managed_hint');
        echo '</p></div>';
    }
    ?>

    <div class="form-group">
        <label for="username"><?= Yii::t('user', 'login_username') ?>:</label>
        <input class="form-control" name="username" id="username" type="text" autofocus required
               placeholder="<?= Html::encode(Yii::t('user', 'login_email_placeholder')) ?>"
               autocomplete="username" value="<?= Html::encode($preUsername) ?>">
    </div>

    <div class="form-group">
        <label for="passwordInput"><?= Yii::t('user', 'login_password') ?>:</label>
        <input type="password" name="password" id="passwordInput" required class="form-control"
               autocomplete="current-password" data-min-len="<?= $pwMinLen ?>">
    </div>
    <?php
    if ($supportsCreating) {
        ?>
        <div class="form-group hidden" id="pwdConfirm">
            <label for="passwordConfirm"><?= Yii::t('user', 'login_password_rep') ?>:</label>
            <input type="password" name="passwordConfirm" id="passwordConfirm" class="form-control">
        </div>

        <div class="form-group hidden" id="regName">
            <label for="name"><?= Yii::t('user', 'login_create_name') ?>:</label>
            <input type="text" value="<?= Html::encode($preName) ?>" name="name" id="name" class="form-control">
        </div>
        <?php
        if ($controller->getParams()->dataPrivacyCheckbox) {
            ?>
            <div class="form-group hidden checkbox" id="regConfirmation">
                <label>
                    <input type="checkbox" name="confirmation" id="confirmation">
                    <?= Yii::t('user', 'login_confirm_registration') ?>:
                </label>
            </div>
            <?php
        }
    }
    ?>

    <div class="row">
        <div class="col-md-6">
            <button type="submit" class="btn btn-primary" name="loginusernamepassword">
                <span id="loginStr"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                    <?= Yii::t('user', 'login_btn_login') ?></span>
                <?php
                if ($supportsCreating) {
                    ?>
                    <span id="createStr"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                    <?= Yii::t('user', 'login_btn_create') ?></span>
                    <?php
                }
                ?>
            </button>
        </div>

        <?php
        if ($externalAuthenticator === null || $externalAuthenticator->supportsResetPassword()) {
            ?>
            <div class="col-md-6 passwordRecovery">
                <?= Html::a(Yii::t('user', 'login_forgot_pw'), UrlHelper::createUrl('user/recovery')) ?>
            </div>
            <?php
        } elseif ($externalAuthenticator && $externalAuthenticator->resetPasswordAlternativeLink()) {
            ?>
            <div class="col-md-6 passwordRecovery">
                <?= Html::a(Yii::t('user', 'login_forgot_pw'), $externalAuthenticator->resetPasswordAlternativeLink()) ?>
            </div>
            <?php
        }
        ?>
    </div>
    <?php
    echo Html::endForm();

    echo '</div>
    </section>';
}


if ($params->isSamlActive()) {
    $hide_ww_login = !in_array(SiteSettings::LOGIN_WURZELWERK, $loginMethods);
    echo '<section class="loginSimplesaml">';
    if ($hide_ww_login) {
        echo '<div class="content">
        <a href="#" onClick="$(\'#admin_login_saml\').toggleClass(\'hidden\'); return false;">Admin-Login</a>
    </div>
    <div id="admin_login_saml" class="hidden">';
    }

    echo '<h2 class="green">&quot;Grünes Netz&quot;-Login (Wurzelwerk)</h2>
    <div class="content row">';

    $action = $params->domainPlain . 'loginsaml';
    echo Html::beginForm($action, 'post', ['class' => 'col-sm-4', 'id' => 'samlLoginForm']);

    $absoluteBack = UrlHelper::absolutizeLink($backUrl);
    echo '
        <input type="hidden" name="backUrl" value="' . Html::encode($absoluteBack) . '">
        <button type="submit" class="btn btn-primary" name="samlLogin">
            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Einloggen
    </button>';

    echo Html::endForm();
    echo '<div id="loginSamlHint">
    <strong>Hinweis:</strong> Hier wirst du auf eine Seite unter "https://saml.gruene.de/" umgeleitet,
    die vom Bundesverband betrieben wird.<br>Dort musst du dein Benutzer*innenname/Passwort des Grünen Netzes
    (Wurzelwerk) eingeben. Dein Passwort bleibt dabei geheim und wird <i>nicht</i> an Antragsgrün übermittelt.
    <br><br>
    <strong>Zugangsdaten vergessen?</strong> Klicke auf „Einloggen” und auf der folgenden Seite auf „Passwort vergessen?”.
        </div>
</div>';

    if ($hide_ww_login) {
        echo '</div>';
    }
    echo '</section>';
}

$loginText = \app\models\db\ConsultationText::getPageData($controller->site, $controller->consultation, 'login_post');
if ($loginText && trim($loginText->text) !== '') {
    echo '<div class="content contentPage">';
    echo $loginText->text;
    echo '</div>';
}

views/user/recovery.php
<?php

use app\components\UrlHelper;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var string $preEmail
 * @var string $preCode
 */

/** @var \app\controllers\UserController $controller */
$controller = $this->context;
$layout     = $controller->layoutParams;

$this->title = Yii::t('user', 'recover_title');
$layout->addBreadcrumb('Passwort');
$layout->robotsNoindex = true;

echo '<h1>' . Yii::t('user', 'recover_title') . '</h1>';

echo $controller->showErrors();

$url = UrlHelper::createUrl('user/recovery');

echo Html::beginForm($url, 'post', ['class' => 'sendConfirmationForm', 'aria-labelledby' => 'step1title']);

?>
    <h2 class="green" id="step1title"><?= Yii::t('user', 'recover_step1') ?></h2>
    <div class="content">
        <div class="row">
            <div class="form-group col-sm-6">
                <label for="sendEmail"><?= Yii::t('user', 'recover_email') ?>:</label>
                <input class="form-control" name="email" id="sendEmail" type="email" required
                       placeholder="<?= Html::encode(Yii::t('user', 'recover_email_place')) ?>" value="">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <button type="submit" class="btn btn-primary" name="send">
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                    <?= Yii::t('user', 'recover_send_email') ?>
                </button>
            </div>
        </div>
    </div>
<?= Html::endForm() ?>

<?= Html::beginForm($url, 'post', ['class' => 'resetPasswortForm', 'aria-labelledby' => 'step2title']) ?>
    <h2 class="green" id="step2title"><?= Yii::t('user', 'recover_step2') ?></h2>
    <div class="content">
        <div class="row">
            <div class="form-group col-sm-6">
                <label for="recoveryEmail"><?= Yii::t('user', 'recover_email') ?>:</label>
                <input class="form-control" name="email" id="recoveryEmail" type="email" required
                       placeholder="<?= Html::encode(Yii::t('user', 'recover_email_place')) ?>"
                       value="<?= Html::encode($preEmail) ?>">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-6">
                <label for="recoveryCode"><?= Yii::t('user', 'recover_code') ?>:</label>
                <input class="form-control" name="recoveryCode" id="recoveryCode" type="text" required
                       value="<?= Html::encode($preCode) ?>">
            </div>
        </div>

        <div class="row">
            <div class="form-group col-sm-6">
                <label for="recoveryPassword"><?= Yii::t('user', 'recover_new_pwd') ?>:</label>
                <input class="form-control" name="newPassword" id="recoveryPassword" type="password" required value="">
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <button type="submit" class="btn btn-primary" name="recover">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                    <?= Yii::t('user', 'recover_set_pwd') ?>
                </button>
            </div>
        </div>
    </div>

<?php
echo Html::endForm();

if ($preCode != '' && $preEmail != '') {
    $layout->addOnLoadJS('$("#recoveryPassword").scrollintoview().focus();');
}

views/user/recovery_confirmed.php
<?php

/**
 * @var yii\web\View $this
 */

$this->title = Yii::t('user', 'recovered_title');
?>

<h1><?= Yii::t('user', 'recovered_title') ?></h1>

<div class="content">

    <div class="alert alert-success" role="alert">
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
        <?= Yii::t('user', 'recovered_msg') ?>
    </div>

</div>

views/user/registration_confirmed.php
<?php

/**
 * @var yii\web\View $this
 * @var bool $needsAdminScreening
 */

$this->title = Yii::t('user', 'confirmed_title');
?>

<h1><?= Yii::t('user', 'confirmed_title') ?></h1>

<div class="content">
    <?php
    if ($needsAdminScreening) {
        ?>
        <div class="alert alert-info confirmedScreeningMsg" role="alert">
            <span class="glyphicon glyphicon-alert" aria-hidden="true"></span>
            <?= Yii::t('user', 'confirmed_screening_msg') ?>
        </div>
        <?php
    } else {
        ?>
        <div class="alert alert-success" role="alert">
            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
            <?= Yii::t('user', 'confirmed_msg') ?>
        </div>
        <?php
    }
    ?>
</div>